### ISSUE TITLE
dependency to the ssh identity file

### ISSUE THREAD

**Issue by michilu** [stormcat24/protodep#26]
Can not get from the `https` scheme repositories.

Trying to get the examples from the `grpc-gateway`:
https://github.com/grpc-ecosystem/grpc-gateway/tree/v1.4.1/examples/proto/examplepb

```console
$ cat > protodep.toml <<EOF
proto_outdir = "./proto"

[[dependencies]]
  target = "github.com/grpc-ecosystem/grpc-gateway/examples/proto/examplepb"
  revision = "v1.4.1"
  path = "grpc-gateway/examplepb"
EOF
```

```console
$ protodep up
[INFO] force update = false
[INFO] identity file = id_rsa
[INFO] use SSH protocol
[INFO] Getting github.com/grpc-ecosystem/grpc-gateway panic: x509: decryption password incorrect

goroutine 1 [running]:
github.com/stormcat24/protodep/helper.(*AuthProviderWithSSH).AuthMethod(0xc4201838e0, 0xb, 0xc420186eb0)
        $GOPATH/src/github.com/stormcat24/protodep/helper/auth.go:48 +0xa8
github.com/stormcat24/protodep/repository.(*GitHubRepository).Open(0xc4200e4780, 0xc4200e4780, 0x0, 0x0)
        $GOPATH/src/github.com/stormcat24/protodep/repository/git.go:78 +0x232
github.com/stormcat24/protodep/service.(*SyncImpl).Resolve(0xc4200b7a80, 0xc4200b7a00, 0x0, 0x0)
        $GOPATH/src/github.com/stormcat24/protodep/service/sync.go:59 +0x711
github.com/stormcat24/protodep/cmd.glob..func1(0x18e5080, 0x1908208, 0x0, 0x0, 0x0, 0x0)
        $GOPATH/src/github.com/stormcat24/protodep/cmd/up.go:61 +0x41a
github.com/spf13/cobra.(*Command).execute(0x18e5080, 0x1908208, 0x0, 0x0, 0x18e5080, 0x1908208)
        $GOPATH/src/github.com/spf13/cobra/command.go:762 +0x468
github.com/spf13/cobra.(*Command).ExecuteC(0x18e4e20, 0x1, 0xc42010ff78, 0x100620c)
        $GOPATH/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0x18e4e20, 0x1, 0x0)
        $GOPATH/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/stormcat24/protodep/cmd.Execute()
        $GOPATH/src/github.com/stormcat24/protodep/cmd/root.go:37 +0x2d
main.main()
        $GOPATH/src/github.com/stormcat24/protodep/main.go:6 +0x20
```

I have `.ssh` directory in $HOME.

```console
$ test -d ~/.ssh; echo $?
0
```

Trying to set current directory to $HOME:

```console
$ HOME=$(pwd) protodep up
[INFO] force update = false
[INFO] identity file = id_rsa
[INFO] use SSH protocol
[INFO] Getting github.com/grpc-ecosystem/grpc-gateway panic: open $(pwd)/.ssh/id_rsa: no such file or directory

goroutine 1 [running]:
github.com/stormcat24/protodep/helper.(*AuthProviderWithSSH).AuthMethod(0xc420183880, 0xb, 0xc420186ea0)
        $GOPATH/src/github.com/stormcat24/protodep/helper/auth.go:48 +0xa8
github.com/stormcat24/protodep/repository.(*GitHubRepository).Open(0xc4200e4780, 0xc4200e4780, 0x0, 0x0)
        $GOPATH/src/github.com/stormcat24/protodep/repository/git.go:78 +0x232
github.com/stormcat24/protodep/service.(*SyncImpl).Resolve(0xc4200b7a80, 0xc4200b7a00, 0x0, 0x0)
        $GOPATH/src/github.com/stormcat24/protodep/service/sync.go:59 +0x711
github.com/stormcat24/protodep/cmd.glob..func1(0x18e5080, 0x1908208, 0x0, 0x0, 0x0, 0x0)
        $GOPATH/src/github.com/stormcat24/protodep/cmd/up.go:61 +0x41a
github.com/spf13/cobra.(*Command).execute(0x18e5080, 0x1908208, 0x0, 0x0, 0x18e5080, 0x1908208)
        $GOPATH/src/github.com/spf13/cobra/command.go:762 +0x468
github.com/spf13/cobra.(*Command).ExecuteC(0x18e4e20, 0x1, 0xc42010df78, 0x100620c)
        $GOPATH/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0x18e4e20, 0x1, 0x0)
        $GOPATH/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/stormcat24/protodep/cmd.Execute()
        $GOPATH/src/github.com/stormcat24/protodep/cmd/root.go:37 +0x2d
main.main()
        $GOPATH/src/github.com/stormcat24/protodep/main.go:6 +0x20
```

Trying via an empty $HOME:

```console
$ HOME= protodep up
[INFO] force update = false
[INFO] identity file = id_rsa
Error: exec: "getent": executable file not found in $PATH
Usage:
  protodep up [flags]

Flags:
  -f, --force                  update locked file and .proto vendors
  -h, --help                   help for up
  -i, --identity-file string   set the identity file for SSH (default "id_rsa")
  -p, --password string        set the password for SSH

exec: "getent": executable file not found in $PATH
```

**Comment by stormcat24** [comment]
Thank you 🙏 
This issue is solved in #42
